name: Release and Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract release version
        id: vars
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:${{ env.RELEASE_TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:${{ env.RELEASE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:${{ env.RELEASE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:latest

      - name: Clone ms-users-infra and update image tag
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/ArturBatista/ms-users-infra.git
          cd ms-users-infra
          sed -i "s|image: .*/ms-users:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/ms-users:${{ env.RELEASE_TAG }}|g" apps/ms-users/base/deployment.yaml
          git commit -am "Update ms-users image to tag ${{ env.RELEASE_TAG }}"
          git push origin main
